apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zero-limit
spec:
  replicas: 1
  template:
    metadata:
      name: zero-limit
      labels:
        app: zero-limit
    spec:
      containers:
      - name: zero-limit
        image: nginx
        resources:
          requests:
            memory: 0
            cpu: 0
          limits:
            memory: 0
            cpu: 0